#!/usr/bin/env python3
"""Write the scythe's blade paths, recorded while the swings are keyed, as a C# table.

    blender -b player.blend -P tools/visuals/blender/build_player.py -- --out player.blend \\
        --rekey swing1,swing2,swing3 --paths art/production/candidates/player/swing_paths.json
    tools/visuals/.venv/bin/python tools/visuals/blade_paths.py \\
        --paths art/production/candidates/player/swing_paths.json

The game draws the Death Flame ribbon of a swing from the core in the scythe's iron collar, so
it follows the rendered blade in timing, heading and height. Each sample holds the swing's
progress, the core's heading in game degrees from the aim (positive clockwise on screen), its
level distance from the feet and its height above the floor, both in metres.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TARGET = REPO / "src" / "TheLostSoulOfFire" / "Rendering" / "ScytheBladePaths.cs"

HEADER = '''// Generated by tools/visuals/blade_paths.py from the keyed swings (build_player.py); do not edit.
using System;

namespace TheLostSoulOfFire.Rendering;

/// <summary>
/// Where the Death Flame core in the scythe's collar and the blade's tip are during each swing of
/// the rendered figure: progress, heading in degrees from the aim (positive clockwise on screen),
/// level distance from the feet and height above the floor in metres. Presentation only.
/// </summary>
public static partial class ScytheBladePaths
{
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--paths", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=TARGET)
    args = parser.parse_args()
    data = json.loads(args.paths.read_text())
    lines = [HEADER]
    names = []
    for point, prefix in (("core", "Swing"), ("tip", "Tip")):
        for step in (1, 2, 3):
            samples = data[f"swing{step}"]
            rows = []
            for sample in samples:
                forward, left, up = sample[point]
                heading = math.degrees(math.atan2(-left, forward))
                distance = math.hypot(forward, left)
                rows.append(f"        new({sample['p']:.4f}f, {heading:.2f}f, {distance:.4f}f, {up:.4f}f),")
            name = f"{prefix}{step}"
            names.append(name)
            lines.append(f"    private static readonly Sample[] {name} =\n    [\n" + "\n".join(rows) + "\n    ];\n")
    lines.append("    private static ReadOnlySpan<Sample> Of(int step) => step switch\n    {\n"
                 "        1 => Swing1,\n        2 => Swing2,\n        _ => Swing3\n    };\n")
    lines.append("    /// <summary>The blade's tip during each swing, in the same terms as the core.</summary>\n"
                 "    private static ReadOnlySpan<Sample> OfTip(int step) => step switch\n    {\n"
                 "        1 => Tip1,\n        2 => Tip2,\n        _ => Tip3\n    };\n}\n")
    args.out.write_text("\n".join(lines))
    print(f"BLADE_PATHS_DONE {args.out}")


if __name__ == "__main__":
    main()
