// Generated by tools/visuals/blade_paths.py from the keyed swings (build_player.py); do not edit.
using System;

namespace TheLostSoulOfFire.Rendering;

/// <summary>
/// Where the Death Flame core in the scythe's collar and the blade's tip are during each swing of
/// the rendered figure: progress, heading in degrees from the aim (positive clockwise on screen),
/// level distance from the feet and height above the floor in metres. Presentation only.
/// </summary>
public static partial class ScytheBladePaths
{

    private static readonly Sample[] Swing1 =
    [
        new(0.0000f, -81.74f, 1.4728f, 1.3447f),
        new(0.0769f, -76.35f, 1.4746f, 1.3236f),
        new(0.1538f, -58.34f, 1.5029f, 1.2498f),
        new(0.2308f, -17.39f, 1.5985f, 1.0552f),
        new(0.3077f, 25.67f, 1.6573f, 0.8408f),
        new(0.3846f, 49.34f, 1.6322f, 0.7314f),
        new(0.4615f, 62.25f, 1.5985f, 0.6774f),
        new(0.5385f, 71.27f, 1.5602f, 0.6428f),
        new(0.6154f, 74.25f, 1.5360f, 0.6332f),
        new(0.6923f, 73.18f, 1.5247f, 0.6557f),
        new(0.7692f, 71.02f, 1.5164f, 0.6954f),
        new(0.8462f, 68.87f, 1.5085f, 0.7370f),
        new(0.9231f, 66.01f, 1.5011f, 0.7939f),
        new(1.0000f, 64.54f, 1.4958f, 0.8256f),
    ];

    private static readonly Sample[] Swing2 =
    [
        new(0.0000f, 83.98f, 1.3841f, 0.3919f),
        new(0.0667f, 79.19f, 1.3733f, 0.3640f),
        new(0.1333f, 66.12f, 1.3646f, 0.3328f),
        new(0.2000f, 40.69f, 1.4663f, 0.4944f),
        new(0.2667f, 8.79f, 1.6028f, 0.8313f),
        new(0.3333f, -19.94f, 1.6529f, 1.2247f),
        new(0.4000f, -39.33f, 1.6130f, 1.5023f),
        new(0.4667f, -54.05f, 1.5555f, 1.6933f),
        new(0.5333f, -67.54f, 1.4857f, 1.8331f),
        new(0.6000f, -76.63f, 1.4274f, 1.9158f),
        new(0.6667f, -77.35f, 1.4129f, 1.9115f),
        new(0.7333f, -76.41f, 1.4118f, 1.8742f),
        new(0.8000f, -75.14f, 1.4130f, 1.8306f),
        new(0.8667f, -73.91f, 1.4110f, 1.7939f),
        new(0.9333f, -72.39f, 1.4088f, 1.7552f),
        new(1.0000f, -71.77f, 1.4066f, 1.7369f),
    ];

    private static readonly Sample[] Swing3 =
    [
        new(0.0000f, -100.35f, 1.4326f, 1.7032f),
        new(0.0400f, -106.59f, 1.3976f, 1.8457f),
        new(0.0800f, -116.15f, 1.3348f, 2.0689f),
        new(0.1200f, -122.76f, 1.3222f, 2.1758f),
        new(0.1600f, -128.13f, 1.3286f, 2.2416f),
        new(0.2000f, -131.05f, 1.3457f, 2.2684f),
        new(0.2400f, -112.58f, 1.4412f, 1.9241f),
        new(0.2800f, -75.28f, 1.4921f, 1.2443f),
        new(0.3200f, -35.26f, 1.5119f, 0.7518f),
        new(0.3600f, 0.96f, 1.5633f, 0.4254f),
        new(0.4000f, 23.97f, 1.5700f, 0.3451f),
        new(0.4400f, 42.61f, 1.5765f, 0.2973f),
        new(0.4800f, 57.57f, 1.5845f, 0.2723f),
        new(0.5200f, 69.25f, 1.5926f, 0.2701f),
        new(0.5600f, 79.20f, 1.5943f, 0.2771f),
        new(0.6000f, 87.67f, 1.5909f, 0.2889f),
        new(0.6400f, 94.62f, 1.5853f, 0.3032f),
        new(0.6800f, 100.30f, 1.5796f, 0.3188f),
        new(0.7200f, 105.76f, 1.5726f, 0.3400f),
        new(0.7600f, 110.07f, 1.5659f, 0.3659f),
        new(0.8000f, 111.99f, 1.5609f, 0.3949f),
        new(0.8400f, 111.51f, 1.5571f, 0.4351f),
        new(0.8800f, 109.93f, 1.5531f, 0.4881f),
        new(0.9200f, 107.95f, 1.5491f, 0.5417f),
        new(0.9600f, 106.30f, 1.5460f, 0.5834f),
        new(1.0000f, 105.69f, 1.5453f, 0.6002f),
    ];

    private static readonly Sample[] Tip1 =
    [
        new(0.0000f, -38.14f, 1.4174f, 1.5423f),
        new(0.0769f, -32.70f, 1.4237f, 1.4995f),
        new(0.1538f, -15.70f, 1.4801f, 1.3808f),
        new(0.2308f, 22.45f, 1.5938f, 1.1589f),
        new(0.3077f, 64.19f, 1.6453f, 0.9216f),
        new(0.3846f, 88.58f, 1.6169f, 0.7940f),
        new(0.4615f, 102.40f, 1.5825f, 0.7190f),
        new(0.5385f, 112.40f, 1.5490f, 0.6711f),
        new(0.6154f, 115.93f, 1.5348f, 0.6585f),
        new(0.6923f, 114.96f, 1.5374f, 0.6903f),
        new(0.7692f, 112.78f, 1.5447f, 0.7487f),
        new(0.8462f, 110.59f, 1.5511f, 0.8122f),
        new(0.9231f, 107.72f, 1.5544f, 0.8830f),
        new(1.0000f, 106.27f, 1.5559f, 0.9191f),
    ];

    private static readonly Sample[] Tip2 =
    [
        new(0.0000f, 37.01f, 1.3502f, 0.3183f),
        new(0.0667f, 31.66f, 1.3333f, 0.3091f),
        new(0.1333f, 18.58f, 1.3455f, 0.3154f),
        new(0.2000f, -3.29f, 1.4512f, 0.4739f),
        new(0.2667f, -31.20f, 1.5913f, 0.8079f),
        new(0.3333f, -58.70f, 1.6345f, 1.2815f),
        new(0.4000f, -79.22f, 1.5805f, 1.5807f),
        new(0.4667f, -95.57f, 1.5165f, 1.7744f),
        new(0.5333f, -111.10f, 1.4510f, 1.9080f),
        new(0.6000f, -121.90f, 1.4054f, 1.9843f),
        new(0.6667f, -122.90f, 1.4043f, 1.9800f),
        new(0.7333f, -121.75f, 1.4171f, 1.9433f),
        new(0.8000f, -120.20f, 1.4331f, 1.8968f),
        new(0.8667f, -118.79f, 1.4461f, 1.8533f),
        new(0.9333f, -117.13f, 1.4561f, 1.8106f),
        new(1.0000f, -116.44f, 1.4616f, 1.7910f),
    ];

    private static readonly Sample[] Tip3 =
    [
        new(0.0000f, -54.91f, 1.3787f, 1.8139f),
        new(0.0400f, -58.86f, 1.2766f, 1.9518f),
        new(0.0800f, -64.54f, 1.1313f, 2.1577f),
        new(0.1200f, -69.71f, 1.0628f, 2.2510f),
        new(0.1600f, -74.82f, 1.0273f, 2.3064f),
        new(0.2000f, -78.20f, 1.0122f, 2.3286f),
        new(0.2400f, -64.42f, 1.1331f, 2.0314f),
        new(0.2800f, -30.71f, 1.3472f, 1.3731f),
        new(0.3200f, 7.05f, 1.5001f, 0.8616f),
        new(0.3600f, 41.37f, 1.5872f, 0.5218f),
        new(0.4000f, 64.16f, 1.5969f, 0.4398f),
        new(0.4400f, 82.66f, 1.6016f, 0.3889f),
        new(0.4800f, 97.50f, 1.6046f, 0.3585f),
        new(0.5200f, 109.08f, 1.6066f, 0.3486f),
        new(0.5600f, 119.06f, 1.6040f, 0.3476f),
        new(0.6000f, 127.67f, 1.5981f, 0.3518f),
        new(0.6400f, 134.80f, 1.5916f, 0.3592f),
        new(0.6800f, 140.64f, 1.5864f, 0.3688f),
        new(0.7200f, 146.27f, 1.5810f, 0.3838f),
        new(0.7600f, 150.72f, 1.5774f, 0.4036f),
        new(0.8000f, 152.72f, 1.5774f, 0.4268f),
        new(0.8400f, 152.22f, 1.5822f, 0.4665f),
        new(0.8800f, 150.56f, 1.5902f, 0.5263f),
        new(0.9200f, 148.50f, 1.5982f, 0.5903f),
        new(0.9600f, 146.77f, 1.6046f, 0.6416f),
        new(1.0000f, 146.09f, 1.6091f, 0.6626f),
    ];

    private static ReadOnlySpan<Sample> Of(int step) => step switch
    {
        1 => Swing1,
        2 => Swing2,
        _ => Swing3
    };

    /// <summary>The blade's tip during each swing, in the same terms as the core.</summary>
    private static ReadOnlySpan<Sample> OfTip(int step) => step switch
    {
        1 => Tip1,
        2 => Tip2,
        _ => Tip3
    };
}
