// Generated by tools/visuals/blade_paths.py from the keyed swings (build_player.py); do not edit.
using System;

namespace TheLostSoulOfFire.Rendering;

/// <summary>
/// Where the Death Flame core in the scythe's collar is during each swing of the rendered
/// figure: progress, heading in degrees from the aim (positive clockwise on screen), level
/// distance from the feet and height above the floor in metres. Presentation only.
/// </summary>
public static partial class ScytheBladePaths
{

    private static readonly Sample[] Swing1 =
    [
        new(0.0000f, -82.35f, 1.1539f, 1.3182f),
        new(0.0769f, -76.97f, 1.1555f, 1.3000f),
        new(0.1538f, -58.61f, 1.1830f, 1.2367f),
        new(0.2308f, -17.23f, 1.2787f, 1.0718f),
        new(0.3077f, 25.84f, 1.3414f, 0.8931f),
        new(0.3846f, 49.44f, 1.3196f, 0.8011f),
        new(0.4615f, 62.31f, 1.2880f, 0.7561f),
        new(0.5385f, 71.32f, 1.2513f, 0.7273f),
        new(0.6154f, 74.38f, 1.2275f, 0.7194f),
        new(0.6923f, 73.43f, 1.2155f, 0.7390f),
        new(0.7692f, 71.39f, 1.2060f, 0.7735f),
        new(0.8462f, 69.36f, 1.1967f, 0.8094f),
        new(0.9231f, 66.60f, 1.1877f, 0.8580f),
        new(1.0000f, 65.21f, 1.1816f, 0.8850f),
    ];

    private static readonly Sample[] Swing2 =
    [
        new(0.0000f, 84.12f, 1.0885f, 0.5150f),
        new(0.0667f, 79.55f, 1.0796f, 0.4916f),
        new(0.1333f, 66.42f, 1.0731f, 0.4653f),
        new(0.2000f, 40.71f, 1.1634f, 0.5982f),
        new(0.2667f, 8.59f, 1.2855f, 0.8743f),
        new(0.3333f, -20.19f, 1.3339f, 1.1973f),
        new(0.4000f, -39.61f, 1.3016f, 1.4282f),
        new(0.4667f, -54.35f, 1.2533f, 1.5877f),
        new(0.5333f, -67.92f, 1.1929f, 1.7037f),
        new(0.6000f, -77.11f, 1.1412f, 1.7726f),
        new(0.6667f, -77.96f, 1.1265f, 1.7688f),
        new(0.7333f, -77.15f, 1.1229f, 1.7369f),
        new(0.8000f, -76.00f, 1.1213f, 1.6996f),
        new(0.8667f, -74.88f, 1.1175f, 1.6676f),
        new(0.9333f, -73.45f, 1.1135f, 1.6337f),
        new(1.0000f, -72.92f, 1.1105f, 1.6175f),
    ];

    private static readonly Sample[] Swing3 =
    [
        new(0.0000f, -100.58f, 1.1293f, 1.6005f),
        new(0.0400f, -107.63f, 1.1050f, 1.7175f),
        new(0.0800f, -118.05f, 1.0642f, 1.9023f),
        new(0.1200f, -125.11f, 1.0651f, 1.9911f),
        new(0.1600f, -130.70f, 1.0810f, 2.0458f),
        new(0.2000f, -133.77f, 1.1026f, 2.0682f),
        new(0.2400f, -115.51f, 1.1638f, 1.7785f),
        new(0.2800f, -77.33f, 1.1766f, 1.2179f),
        new(0.3200f, -35.63f, 1.1970f, 0.8095f),
        new(0.3600f, 1.32f, 1.2626f, 0.5353f),
        new(0.4000f, 24.40f, 1.2736f, 0.4658f),
        new(0.4400f, 43.06f, 1.2825f, 0.4239f),
        new(0.4800f, 58.01f, 1.2918f, 0.4019f),
        new(0.5200f, 69.68f, 1.3001f, 0.3999f),
        new(0.5600f, 79.62f, 1.3014f, 0.4060f),
        new(0.6000f, 88.07f, 1.2973f, 0.4164f),
        new(0.6400f, 95.04f, 1.2909f, 0.4289f),
        new(0.6800f, 100.73f, 1.2845f, 0.4426f),
        new(0.7200f, 106.21f, 1.2764f, 0.4611f),
        new(0.7600f, 110.55f, 1.2684f, 0.4838f),
        new(0.8000f, 112.53f, 1.2620f, 0.5091f),
        new(0.8400f, 112.15f, 1.2565f, 0.5444f),
        new(0.8800f, 110.66f, 1.2504f, 0.5910f),
        new(0.9200f, 108.77f, 1.2444f, 0.6381f),
        new(0.9600f, 107.20f, 1.2399f, 0.6747f),
        new(1.0000f, 106.65f, 1.2386f, 0.6894f),
    ];

    private static ReadOnlySpan<Sample> Of(int step) => step switch
    {
        1 => Swing1,
        2 => Swing2,
        _ => Swing3
    };
}
